### ISSUE TITLE
Windows can run pi3d.Display.create() only when sample=0

### ISSUE THREAD

**Issue by utthawut** [utthawut/RaspBilliard#2]
## The Problem

Windows cannot run pi3d.Display.create() function when sample > 0
## The Cause

I'm not sure but in create_display its error generated as below
    _assert self.context != EGL_NO_CONTEXT_
Paddy might know the cause of problem more than me
## How to Solve

Maybe use checking platform like below

```
if platform == "WINDOWS":
     DISPLAY = pi3d.Display.create(x=100, y=100, samples=0)
else:
    DISPLAY = pi3d.Display.create(x=100, y=100, samples=2)


```

**Comment by paddywwoof** [comment]
EGL_SAMPLES doesn't seem to be implemented in the [ANGLE source code](https://github.com/google/angle/blob/bc4c4bc5f6659f3dc815b6b1d0c68ad8ab80eea2/src/libANGLE/renderer/d3d/d3d11/RenderTarget11.cpp#L416) yet so it makes sense to check for this in the pi3d source code - I will change it accordingly (i.e. in pi3d/Display.create())
