### ISSUE TITLE
rotation vector occasionally is wrong

### ISSUE THREAD

**Issue by utthawut** [utthawut/RaspBilliard#4]
**Problem:**
We can notice the ball rolling/rotation is wrong

**Comment by utthawut** [comment]
After debugging, the problem may be inside "move_rotate" function.
How to test:
1. In main.py
`CamRotation = 90  # rotation of camera, to start game with 90 degress`
2. in calculate.py
in "PoolBall" Constructor
`if name == 'Cue_Ball':`
`self.tex = pi3d.Texture('media/textures/Pool_Ball_7.png')  # This will let you see rotation weird`
`else:`
`self.tex = pi3d.Texture('media/textures/{}.png'.format(name))`
and comment below code (don't caer about changing heading_angle,
in "update_state_change" method
`heading_angle_changed = ((np.degrees(
                    np.arctan2([self.v[common.X_AXIS].real], [self.v[common.Y_AXIS].real])[0])))
                self.heading_angle = (self.heading_angle - heading_angle_changed + 180) % 360 - 180`
3. running main.py (Don't move your mouse),please press key 'k' for 2 times and then press key 'g' for 4-5 times, you will then see weird for ball rotation.

**Comment by paddywwoof** [comment]
hopefully fixed by `|=` in main.py commit cc1dcd2
